# ***** Telegram TOKEN and parameters Definition *****
TOKEN = "6535153154:AAGuymX2nG6wrkfxVxe6Bqmqef2QMJRN0Cs"
CHANNEL_NAME = "@amazoncheapdealsop"

# ***** BOT ACTIVITY TIME *****
MIN_HOUR = 9
MAX_HOUR = 24
PAUSE_MINUTES = 12

# ***** Amazon API Keys and parameters *****
AMAZON_ACCESS_KEY = "<YOUR AMAZON ACCESS KEY>"
AMAZON_SECRET_KEY = "<YOUR AMAZON SECRET KEY>"
PARTNER_TAG = "<YOUR AMAZON PARTNER TAG>"
AMAZON_HOST = "<YOUR AMAZON HOST>"
AMAZON_REGION = "<YOUR AMAZON REGION>"
